# Generated by Django 6.0.5 on 2026-08-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0002_candidate_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='party_slogan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
