# Generated by Django 6.0.5 on 2026-08-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(choices=[('president', 'President'), ('governor', 'Governor'), ('senate president', 'Senate President'), ('local government chairman', 'Local Government Chairman'), ('councillor', 'Councillor'), ('sug president', 'SUG President')], max_length=50),
        ),
    ]
