# Generated by Django 6.0.5 on 2026-08-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('electoral_officer', 'Electoral Officer'), ('candidate', 'Candidate'), ('admin', 'Admin')], default='user', max_length=50),
        ),
    ]
